apiVersion: v1
kind: ResourceQuota
metadata:
  name: tir
  namespace: tir
spec:
  hard:
    pods: "30"
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.memory: 32Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tir
  namespace: tir
spec:
  limits:
    - type: Container
      default:
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
